### ISSUE TITLE
npm install error: npm ERR! cb() never called

### ISSUE THREAD

**Issue by sergeykosik** [marcorinck/ngStart#16] opened 2013-09-28 19:26 UTC
Running the npm install from the root of nsStart project ends with error.
Below is the copy of the last several lines from my terminal:
...
...
...

> phantomjs@1.9.2-1 install /home/sergey/Desktop/ngStart/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
Saving to /home/sergey/Desktop/ngStart/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2
Receiving...
Received 786K...
Received 1572K...
Received 2355K...
Received 3141K...
Received 3924K...
Received 4712K...
Received 5494K...
Received 6275K...
Received 7057K...
Received 7853K...
Received 8637K...
Received 9419K...
Received 10205K...
Received 10996K...
Received 11799K...
Received 12582K...
Received 12967K total.
Extracting tar contents (via spawned process)
Renaming extracted folder /home/sergey/Desktop/ngStart/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-linux-x86_64 -> /home/sergey/Desktop/ngStart/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/sergey/Desktop/ngStart/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! cb() never called!
npm ERR! not ok code 0

**Comment by sergeykosik** [comment] 2013-09-28 19:53
:) Missed to install Karma. The problem was gone once Karma has been installed (npm install -g karma).

**Comment by marcorinck** [comment] 2013-09-28 20:00
you shouldn't need to install karma globally, but anyway, I can't reproduce the problem on windows here.

However, there seem to be some discussion about it, f.i. here: https://github.com/isaacs/npm/issues/2907

Seems to have sth. to do with node/npm itself, some report its gone with node 0.10.18

**Comment by marcorinck** [comment] 2013-09-29 10:53
as this is a problem in npm, it can't be fixed here, see the issue at npm repo: https://github.com/isaacs/npm/issues/2907

closing this

**Closed as completed by marcorinck** 2013-09-29 10:53 UTC
Labels: invalid
